#!/bin/bash
# Software License Agreement (BSD)
#
# Author    Mike Purvis <mpurvis@clearpathrobotics.com>
# Copyright (c) 2014-2015, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
# * Redistributions of source code must retain the above copyright notice, this list of conditions and the
#   following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or
#   promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

ROS_DISTRO=indigo
ROS_CONFIGURATION=desktop_full
ROS_EXTRA_PACKAGES=
ROS_INSTALL_DIR=/opt/ros/${ROS_DISTRO}

do_install()
{
  set -e

  # Homebrew
  if ! hash brew 2>/dev/null; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    echo export PATH='/usr/local/bin:$PATH' >> ~/.bash_profile
    source .bash_profile
    brew doctor
    brew update
  fi

  # XQuartz
  if ! hash xquartz 2>/dev/null; then
    brew install caskroom/cask/brew-cask
    brew cask install xquartz
    echo "Log out and in to finalize XQuartz setup."
    exit 0
  fi

  # Brewed Python
  if [ $(which python) != "/usr/local/bin/python" ]; then
    brew install python
    mkdir -p ~/Library/Python/2.7/lib/python/site-packages
    echo "$(brew --prefix)/lib/python2.7/site-packages" >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth
  fi

  # Homebrew taps for prerequisites
  brew tap ros/deps
  brew tap osrf/simulation
  brew tap homebrew/versions
  brew tap homebrew/science

  # Prerequisites. All of these should in theory be covered by rosdep, but for various reasons
  # they're best installed in advance, due to needing a specific version, or specifying build
  # options, or whatever. Obviously it would be great to migrate these toward purely rosdep.
  brew install cmake libyaml lz4 assimp
  brew install boost --with-python
  brew install opencv --with-qt --with-eigen --with-tbb
  
  # Restore to "ogre" pending: https://github.com/osrf/homebrew-simulation/pull/41
  brew install https://raw.githubusercontent.com/mikepurvis/homebrew-simulation/patch-2/ogre.rb
  
  brew install gazebo5

  # Restore to "ros/deps/pcl" pending: https://github.com/ros/homebrew-deps/pull/9 
  brew install https://github.com/mikepurvis/homebrew-deps/raw/pcl-1.7.2/pcl.rb

  # ROS infrastructure tools
  pip install -U setuptools rosdep rosinstall_generator wstool rosinstall catkin_tools catkin_pkg bloom empy sphinx
  if [ ! -d /etc/ros/rosdep/ ]; then
    sudo rosdep init
  fi
  rosdep update

  # Remove previous workspace if present, create and enter new one.
  WS=${ROS_DISTRO}_${ROS_CONFIGURATION}_ws
  if [ -d "$WS" ]; then
    rm -rf "$WS"
  fi
  mkdir $WS
  pushd $WS
  
  # Standard source install
  rosinstall_generator ${ROS_CONFIGURATION} ${ROS_EXTRA_PACKAGES} --rosdistro ${ROS_DISTRO} --deps --tar > ${WS}.rosinstall
  wstool init -j8 src ${WS}.rosinstall

  # Grabbing these older meshes allows rviz to run with Ogre 1.7 rather than Ogre 1.8+. Although formulae and patches
  # exist to build Ogre 1.9, rviz, and Gazebo together, I have found this approach to be the most solid and consistent.
  if [ -d src/rviz ]; then
    pushd src/rviz/ogre_media/models
    curl https://github.com/ros-visualization/rviz/raw/hydro-devel/ogre_media/models/rviz_cone.mesh > rviz_cone.mesh
    curl https://github.com/ros-visualization/rviz/raw/hydro-devel/ogre_media/models/rviz_cube.mesh > rviz_cube.mesh
    curl https://github.com/ros-visualization/rviz/raw/hydro-devel/ogre_media/models/rviz_cylinder.mesh > rviz_cylinder.mesh
    curl https://github.com/ros-visualization/rviz/raw/hydro-devel/ogre_media/models/rviz_sphere.mesh > rviz_sphere.mesh
    popd
  fi

  # This awful hack papers over a problem with QT's cmake find modules.
  # See: https://github.com/ros-visualization/qt_gui_core/issues/57#issuecomment-122348727
  if [ -d /usr/local/Cellar/qt/4.8.7 ]; then
    pushd /usr/local/Cellar/qt
    ln -s 4.8.7 4.8.6
    popd
  fi

  # Package dependencies.
  rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y --as-root pip:no --skip-keys="ogre gazebo"

  # Parallel build
  sudo mkdir -p ${ROS_INSTALL_DIR}
  sudo chown $USER ${ROS_INSTALL_DIR}
  catkin config --install  --install-space ${ROS_INSTALL_DIR}
  catkin build \
    -DCMAKE_BUILD_TYPE=Release \
    -DPYTHON_LIBRARY=$(python -c "import sys; print sys.prefix")/lib/libpython2.7.dylib \
    -DPYTHON_INCLUDE_DIR=$(python -c "import sys; print sys.prefix")/include/python2.7
  popd
  
  echo "Installation successful, please source the ROS workspace:"
  echo
  echo "  source ${ROS_INSTALL_DIR}/setup.bash"
  echo
}

do_install
