blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DCATKIN_ENABLE_TESTING=1
- -DCMAKE_BUILD_TYPE=Release
- -DCATKIN_ENABLE_TESTING=0
- -DCMAKE_FIND_FRAMEWORK=LAST
- -DPYTHON_EXECUTABLE=/usr/local/bin/python2
- -DPYTHON_LIBRARY=/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
- -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/include/python2.7
devel_layout: linked
devel_space: devel
extend_path: null
install: true
install_space: /opt/ros/lunar
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
